baseURL = "https://py.shoogle.net/paraguay/"
languageCode = "es"
title = "Paraguay"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "paraguay"

[taxonomies]
  shop = "shops"

